### ISSUE TITLE
Publish my PDF's

### ISSUE THREAD

**Issue by sdmeijer** [primo-io/prototype-documentation#11]
May I publish my PDF's for the lasercutter?

**Comment by mat-lo** [comment]
yes, we should think at a system to include derivatives and contributions in a separate menu, like the "languages", probably a "derivatives" folder?

**Comment by sdmeijer** [comment]
I will post them this weekend on my blog. (I have to do some cleanup first). I used the laser cutter yesterday, so now I exactly know what works (and what not).

**Comment by technobly** [comment]
"derivatives" seems appropriate ;-)

**Comment by mat-lo** [comment]
included "derivatives" folder with instructions on how to contribute

**Comment by sdmeijer** [comment]
Done
