### ISSUE TITLE
CNY70-schematic

### ISSUE THREAD

**Issue by sdmeijer** [primo-io/prototype-documentation#12]
Which resistor values did you use for the CNY70.
It's not in the description.

**Comment by mat-lo** [comment]
ah yes that is missing, we followed this scheme:
https://www.dropbox.com/s/r5530c32eu4vdic/CNY70.jpeg

i'm going to add it to the docs

**Comment by mat-lo** [comment]
CNY70 scheme added:
https://github.com/primo-io/prototype-documentation/blob/gh-pages/images/illustrations/cny70-wiring.jpg
