### ISSUE TITLE
Translation instructions

### ISSUE THREAD

**Issue by sdmeijer** [primo-io/prototype-documentation#8]
Isn't it better to move the translation instruction to a separate page (maybe beneath the list of translated languages)?

ATM it's a long scroll down to get to the information about making a Primo.

**Comment by mat-lo** [comment]
that is an idea, we are also thinking of a collapsable div, into the language.md page. 
In this way the instructions are translated in different languages too.

It is a long page, the idea is to structure the various sections on a table of contents, to ease the navigation on the page.

**Comment by sdmeijer** [comment]
Hi Matteo, no problem. It's just an idea.

Is it okay to wait a little before I start translating?
It looks like your still finishing everything.

**Comment by mat-lo** [comment]
Hi Sjoerd, that's a good idea, in fact we are missing some connections and all the code part, we think that by friday tops we should be ready at least with all the content.

**Comment by sdmeijer** [comment]
I'll wait (well I don't have time anyway this week).
I think I can start next week.
Maybe you can add "Nederlands (Dutch)" to the list already, with an information box that this translation is in progress. This way people know it will be translated.

P.S. I will do it the "hard" way (option 3; forking). Can you test it ;-)

**Comment by sdmeijer** [comment]
What's the status of the files. Are they finished (for now) and do you have plans to update them soon?

**Comment by mat-lo** [comment]
This is the release that we will publish the second week of april. 
We think it's going to be like this (maybe some minor changes) for the next future

**Comment by mat-lo** [comment]
we think the documentation is now ready to be published
